[Icon Theme]
Name=Jarvis-White
Comment=High-Tech Minimalist White and Cyan Line-Art Icon Theme for Stark OS and Cinnamon
Inherits=Adwaita,hicolor
Directories=scalable/places,scalable/apps,scalable/status,scalable/actions,48x48/places,48x48/apps

[scalable/places]
Size=64
Type=Scalable
MinSize=16
MaxSize=256
Context=Places

[scalable/apps]
Size=64
Type=Scalable
MinSize=16
MaxSize=256
Context=Applications

[scalable/status]
Size=24
Type=Scalable
MinSize=16
MaxSize=64
Context=Status

[scalable/actions]
Size=24
Type=Scalable
MinSize=16
MaxSize=64
Context=Actions

[48x48/places]
Size=48
Type=Fixed
Context=Places

[48x48/apps]
Size=48
Type=Fixed
Context=Applications
